"""passlib.utils._blowfish - helpers for _slow_bcrypt.py, autogenerated by _gen_blowfish.py"""
#=================================================================
# encipher function
#=================================================================

def bfs_encipher(P, S, l, r):
    """blowfish encipher a single 64-bit block encoded as two 32-bit ints"""

    (p0, p1, p2, p3, p4, p5, p6, p7, p8, p9,
      p10, p11, p12, p13, p14, p15, p16, p17) = P
    S0, S1, S2, S3 = S

    l ^= p0

    # Feistel substitution on left word (round 0)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p1

    # Feistel substitution on right word (round 1)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p2

    # Feistel substitution on left word (round 2)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p3

    # Feistel substitution on right word (round 3)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p4

    # Feistel substitution on left word (round 4)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p5

    # Feistel substitution on right word (round 5)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p6

    # Feistel substitution on left word (round 6)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p7

    # Feistel substitution on right word (round 7)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p8

    # Feistel substitution on left word (round 8)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p9

    # Feistel substitution on right word (round 9)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p10

    # Feistel substitution on left word (round 10)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p11

    # Feistel substitution on right word (round 11)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p12

    # Feistel substitution on left word (round 12)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p13

    # Feistel substitution on right word (round 13)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p14

    # Feistel substitution on left word (round 14)
    r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
          S3[l & 0xff]) & 0xffffffff) ^ p15

    # Feistel substitution on right word (round 15)
    l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
          S3[r & 0xff]) & 0xffffffff) ^ p16

    return r ^ p17, l

def bfs_repeat_encipher(P, S, l, r, count):
    """encipher block of data repeatedly"""

    (p0, p1, p2, p3, p4, p5, p6, p7, p8, p9,
      p10, p11, p12, p13, p14, p15, p16, p17) = P
    S0, S1, S2, S3 = S

    i = 0
    while i < count:

        l ^= p0
        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16


        l, r = r ^ p17, l
        i += 1

    return l, r

def bfs_expand0_rounds(P, S, pass_keys, salt_keys, rounds):
    """optimized version of EKS inner loop, using generator"""

    p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, \
      p10, p11, p12, p13, p14, p15, p16, p17 = P
    S0, S1, S2, S3 = S

    rounds <<= 1
    n = 0
    while n < rounds:

        #=============================================================
        # integrate key
        #=============================================================
        keys = salt_keys if n & 1 else pass_keys

        p0 ^= keys[0]
        p1 ^= keys[1]
        p2 ^= keys[2]
        p3 ^= keys[3]
        p4 ^= keys[4]
        p5 ^= keys[5]
        p6 ^= keys[6]
        p7 ^= keys[7]
        p8 ^= keys[8]
        p9 ^= keys[9]
        p10 ^= keys[10]
        p11 ^= keys[11]
        p12 ^= keys[12]
        p13 ^= keys[13]
        p14 ^= keys[14]
        p15 ^= keys[15]
        p16 ^= keys[16]
        p17 ^= keys[17]

        #=============================================================
        # update P
        #=============================================================
        ##i = 0
        ##while i < 18:
        ##    P[i], P[i+1] = l,r = bfs_encipher(P,S,l,r)
        ##    i += 2

        #------------------------------------------------
        # update P[0] and P[1]
        #------------------------------------------------
        l, r = p0, 0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p0, p1 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[2] and P[3]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p2, p3 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[4] and P[5]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p4, p5 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[6] and P[7]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p6, p7 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[8] and P[9]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p8, p9 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[10] and P[11]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p10, p11 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[12] and P[13]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p12, p13 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[14] and P[15]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p14, p15 = l, r = r ^ p17, l

        #------------------------------------------------
        # update P[16] and P[17]
        #------------------------------------------------
        l ^= p0

        # Feistel substitution on left word (round 0)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p1

        # Feistel substitution on right word (round 1)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p2

        # Feistel substitution on left word (round 2)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p3

        # Feistel substitution on right word (round 3)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p4

        # Feistel substitution on left word (round 4)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p5

        # Feistel substitution on right word (round 5)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p6

        # Feistel substitution on left word (round 6)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p7

        # Feistel substitution on right word (round 7)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p8

        # Feistel substitution on left word (round 8)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p9

        # Feistel substitution on right word (round 9)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p10

        # Feistel substitution on left word (round 10)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p11

        # Feistel substitution on right word (round 11)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p12

        # Feistel substitution on left word (round 12)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p13

        # Feistel substitution on right word (round 13)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p14

        # Feistel substitution on left word (round 14)
        r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
              S3[l & 0xff]) & 0xffffffff) ^ p15

        # Feistel substitution on right word (round 15)
        l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
              S3[r & 0xff]) & 0xffffffff) ^ p16

        p16, p17 = l, r = r ^ p17, l

        #=============================================================
        # update S
        #=============================================================
        # update S
        ##for box in S:
        ##    j = 0
        ##    while j < 256:
        ##        box[j], box[j+1] = l,r = bfs_encipher(P,S,l,r)
        ##        j += 2

        for box in S:
            j = 0
            while j < 256:
                l ^= p0

                # Feistel substitution on left word (round 0)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p1

                # Feistel substitution on right word (round 1)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p2

                # Feistel substitution on left word (round 2)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p3

                # Feistel substitution on right word (round 3)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p4

                # Feistel substitution on left word (round 4)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p5

                # Feistel substitution on right word (round 5)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p6

                # Feistel substitution on left word (round 6)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p7

                # Feistel substitution on right word (round 7)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p8

                # Feistel substitution on left word (round 8)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p9

                # Feistel substitution on right word (round 9)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p10

                # Feistel substitution on left word (round 10)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p11

                # Feistel substitution on right word (round 11)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p12

                # Feistel substitution on left word (round 12)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p13

                # Feistel substitution on right word (round 13)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p14

                # Feistel substitution on left word (round 14)
                r ^= ((((S0[l >> 24] + S1[(l >> 16) & 0xff]) ^ S2[(l >> 8) & 0xff]) +
                      S3[l & 0xff]) & 0xffffffff) ^ p15

                # Feistel substitution on right word (round 15)
                l ^= ((((S0[r >> 24] + S1[(r >> 16) & 0xff]) ^ S2[(r >> 8) & 0xff]) +
                      S3[r & 0xff]) & 0xffffffff) ^ p16

                box[j], box[j+1] = l, r = r ^ p17, l
                j += 2

        #============================================================
        # next half-round
        #============================================================
        n += 1

    #=============================================================
    # update original P array
    #=============================================================
    P[:] = (p0, p1, p2, p3, p4, p5, p6, p7, p8, p9,
      p10, p11, p12, p13, p14, p15, p16, p17)

#=================================================================
# eof
#=================================================================
